### ISSUE TITLE
what arguments to pass when running 'python videohandler.py' as it is showing 'too few arguments' error  

### ISSUE THREAD

**Issue by gazal2708** [scopeInfinity/Video2Description#11]

**Comment by scopeInfinity** [comment]
I guess something similar to `python videohandler.py /path/to/Video2Description`

More flags can be used as per requirement. 

> https://github.com/scopeInfinity/Video2Description/blob/VideoCaption/VideoDataset/videohandler.py#L376-L384

```python
def get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("root_dir", help="path to the project root directory. i.e parent directory of VideoDataset/videohandler.py")
    parser.add_argument("-sc", "--show-count", help="show count for training/validation/test videos", action='store_true')
    parser.add_argument("-d", "--download", help="download more videos to extend dataset", action='store_true')
    parser.add_argument("-ac", "--auto-cache", help="cache all downloaded videos", action='store_true')
    parser.add_argument("-strain", "--show-train", help="show ids for training videos", action='store_true')
    parser.add_argument("-stest", "--show-test", help="show ids for test videos", action='store_true')
    parser.add_argument("-sval", "--show-val", help="show ids for validation videos", action='store_true')
```

Thanks!

**Comment by scopeInfinity** [comment]
Hi @gazal2708 ,
Can you please let me know if the issue is resolved? or if you're still facing issues?

Thanks!

**Comment by gazal2708** [comment]
Sorry for that,
Yeah I got my answer from your explanation about my query.
Thanks


With regards,
Gazal Jain
IIIT Naya Raipur,Pin-493661
Chattisgarh.
B-tech 3rd year CSE(2017-21)
Roll No.17100015
Phone no.9340435946
Email address-1.gazal17100@iiitnr.edu.in
2.gazaljain7523@gmail.com

**Comment by scopeInfinity** [comment]
Great! Thanks for letting me know.
