### ISSUE TITLE
Citing sources

### ISSUE THREAD

**Issue by ajboloor** [scopeInfinity/Video2Description#27]
Can you kindly cite the papers you used for this repo?

**Comment by scopeInfinity** [comment]
Hi Adith,

Thanks for reminding of this.
Added [REFERENCES.md](https://github.com/scopeInfinity/Video2Description/blob/VideoCaption/REFERENCES.md) with the list of relevant papers.

Thanks!

**Comment by scopeInfinity** [comment]
Commit: 6ad1716
