### ISSUE TITLE
Request Failed: Request Failed! Exception caught while generating caption.

### ISSUE THREAD

**Issue by ayushkothari27** [scopeInfinity/Video2Description#28]
I tried the "Try it out" section and set up the prebuilt docker container and tried to run it. Whenever I upload a video to generate captions I get the following error - "Request Failed: Request Failed! Exception caught while generating caption"

![Screenshot from 2020-04-30 21-41-37](https://user-images.githubusercontent.com/29770201/80733557-7f129400-8b2b-11ea-984e-240a0aeb1497.png)

**Comment by scopeInfinity** [comment]
Hi,
Is the issue still present? :/

**Comment by ayushkothari27** [comment]
Hey @scopeInfinity ,
If I remember correctly the issue was for youtube videos which did not have any subtitles.

**Comment by scopeInfinity** [comment]
Okie! Video with/without subtitles shouldn't matter :/.
I guess it will be difficult to reproduce this now.
Just in case if you give it another try and faces the same issue, can you please create the issue again.

Thanks!
