### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by niu1970** [scopeInfinity/Video2Description#29]
博主可否建立一个qq群号，比较方便大家对本项目的交流探讨

**Comment by scopeInfinity** [comment]
Hi,

Does it translate to "Can the blogger establish a qq group number, it is more convenient for everyone to discuss the project"?
Based on quick search it seems like a chat room. I'm not familiar with it, so please feel free to correct me if it's not the case.

Thanks!

**Comment by niu1970** [comment]
Okay, it doesn't matter, thank you very much for taking the time to reply! Since I have just contacted this direction, I would like to trouble you to write a complete use process for your project. That is how to use your pre-trained model and code to achieve the input of a video file to get the output of a video description file. I would appreciate it if you can solve this problem!

**Comment by scopeInfinity** [comment]
For using the pre-trained model to get caption out of the video file. The simplest way is to follow instructions in https://github.com/scopeInfinity/Video2Description#try-it-out.

Please let me know if it works.

Thanks
