### ISSUE TITLE
Docker compose version is not upto date

### ISSUE THREAD

**Issue by Soumi7** [scopeInfinity/Video2Description#30]
## Latest Docker compose version is 2.4

Maybe Update this in the instructions to run after testing

**Comment by scopeInfinity** [comment]
Hi Soumi,

Can you please help me by clarifying what you meant?
 - It seems like the latest docker-compose is 1.26.0.
   - https://github.com/docker/compose/releases 
 - Did you mean 2.4 as Compose file format while the current master uses 3.2?
   - Will update the README.

Thanks!

**Comment by Soumi7** [comment]
Yes exactly! This issue can be closed now.
.

**Comment by scopeInfinity** [comment]
Thanks!
