### ISSUE TITLE
Error predicting captions

### ISSUE THREAD

**Issue by takuyara** [scopeInfinity/Video2Description#32]
I used your pretrained-model to predict my own videos and MSVD videos, but the results goes like "terms bars bars combing combing combing combing combing combing combing combing combing" for all these videos, which doesn't make sense at all. I wonder if you've met the same question. What should I do, plz.

**Comment by scopeInfinity** [comment]
Hi @takuyara ,

I'll take a look again, shortly :) 
Meanwhile, if it's still an issue. Can you please share the mentioned video somehow, if possible?
