### ISSUE TITLE
docker-compose can't find python

### ISSUE THREAD

**Issue by meisa233** [scopeInfinity/Video2Description#39]
Hi! I follow your steps to use docker to build your project.
But there are errors occured.

trans@trans-HVM-domU:~/scene_recognition/Video2Description$ sudo docker-compose up
[sudo] password for trans: 
Creating network "video2description_internal" with the default driver
Creating video2description_backend_1  ... done
Creating video2description_frontend_1 ... done
Attaching to video2description_frontend_1, video2description_backend_1
backend_1   | bash: cannot set terminal process group (-1): Inappropriate ioctl for device
backend_1   | bash: no job control in this shell
backend_1   | bash: python: command not found
video2description_backend_1 exited with code 127

How to solve it?

**Comment by scopeInfinity** [comment]
Hi @meisa233,

Can you try to pull `VideoCaption` branch again and see if it works?
 - https://github.com/scopeInfinity/Video2Description/pull/40
 
 Thanks,
 Gagan
