### ISSUE TITLE
Two step training using multiple caption of a video by spreading over batches

### ISSUE THREAD

**Issue by scopeInfinity** [scopeInfinity/Video2Description#8]
Try observing results for:
 - Step 1: Understand the input
    - Train multiple sentences for a video in a single batch.
    - The model will be learning weights for interpreting the input.
        - Top layers should be learning better about generating VideoContext.
 - Step 2: Prepare the output
   - And hopefully there should be a learning saturation.
   - Assuming top layers can interpret the input.
       - Freeze the weights of some edges?
   - Then spread multiple captions of same videos across the batches.
      - Enforcing model to learn VideoAudioContext to sentence mapping without worrying too much about losing generalization.

**Comment by alokssingh** [comment]
Since for a single video there are multiple captionins available, so how are you processing these captions whether by selecting randomly single caption in each epoch or taking all caption in every epoch?

**Comment by scopeInfinity** [comment]
Hi @aloksingh3110 ,

Based on the recent code it looks like `just_one_caption=True`. So, we are randomly picking up a caption each time a particular video is selected.
 - https://github.com/scopeInfinity/Video2Description/blob/5b8f59708f0cec7d8a9f8b977bd681efa84ad763/src/backend/vpreprocess.py#L85-L86

It's been a long time. So I don't remember if there were any model trained in any other ways or not.
But I guess this is something which can be worked upon.

Thanks!
